### ISSUE TITLE
How to start server?

### ISSUE THREAD

**Issue by zmertens** [anderspitman/issued#1]
How do you start the server?
I feel like I should do `http-server -p 3000` and then something should happen?

**Comment by anderspitman** [comment]
Hey Zach! Yeah sorry you caught this super early. Prototype stage really. Currently need to run it with `node src/index.js`. The port is hard-coded.

**Comment by zmertens** [comment]
```js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/home/zmm/Documents/issued/src/index.js:72:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

~Ok. Not sure what this means. I do have http-server at 3000~ I think I jumped the gun.
